- name: 'Testing different modules'
  hosts: all
  become: yes
  tasks:
    - name: 'Execute a script'
      script: '/tmp/install_vim_httpd.sh'    

    - name: 'Start httpd'
      service:
        name: httpd
        state: started

    - name: 'Add line in file'
      lineinfile:
        path: /var/www/html/index.html
        line: 'Welcome to ansible-beginning course'
        create: yes

    - name: 'Add a user'
      user:
        name: web_user
        uid: 1040
        group: osboxes
        system: true
